version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: event-system-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: event_system
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
  prometheus:
    image: prom/prometheus
    container_name: prometheus    
    ports:
      - "9090:9090"
    volumes:
      - type: bind  # Tipo: montaje directo desde el host
        source: ./docker/prometheus.yml # Ruta en tu computadora (host)
        target: /etc/prometheus/prometheus.yml # Ruta dentro del contenedor
    restart: unless-stopped
  grafana:
    image: grafana/grafana
    container_name: grafana    
    ports:
      - "3001:3000"
    restart: unless-stopped
    depends_on:  
      - prometheus
  redis:
    image: redis:7-alpine
    container_name: event-system-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  
volumes:
  postgres_data:
